### ISSUE TITLE
ModuleNotFoundError: No module named 'connector'

### ISSUE THREAD

**Issue by tomatoneenja** [BillPlayzToday/EpsonProjector#1]
just need to mention i am a huge noob when it comes to python, i kept getting this error code while trying to run the demo

import connector as Connector
ModuleNotFoundError: No module named 'connector'

i've tried everything but for the life of me i cant fix it
would really appreciate some help

**Comment by toni08bit** [comment]
Hi, thanks for reaching out!
Please make sure that you downloaded the `connector.py` file and put it in the **same** directory as the `demo.py` file.

As the error code already kind of explains, the `demo.py` file requires the `connector.py` to be reachable and right next to the `demo.py` file.

It is also important to know that you should always run the script directly from its folder, e.g. `python3 demo.py` and **not** from another folder e.g. `python3 EpsonProjector/demo.py`.

Did that work? If not please send a screenshot of the folder where your `demo.py` file is located in and a screenshot of your terminal window.
